name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: ⚙️ Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip
        pip install buildozer cython

    - name: 📁 Prepare project
      run: |
        mkdir -p assets

    - name: 📥 Download FFmpeg
      run: |
        wget https://files.catbox.moe/g2umsq -O assets/ffmpeg
        chmod +x assets/ffmpeg
        file assets/ffmpeg

    - name: 🔨 Build APK
      run: |
        buildozer android debug

    - name: 📤 Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ezedit-apk
        path: bin/*.apk
